spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000  # 24 hours
      
  cloud:
    discovery:
      enabled: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Disable Eureka
eureka:
  client:
    enabled: false

logging:
  level:
    com.nathaniel.bookbackend: DEBUG
