server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # CORS handled manually in AuthenticationFilter
      # Routes are configured in Java (GatewayConfig.java)
            
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    com.nathaniel.booktracker.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Disable Eureka
eureka:
  client:
    enabled: false
